### ISSUE TITLE
Support for disabling Checkbox

### ISSUE THREAD

**Issue by prscX** [torifat/react-native-bem-check-box#4]
Hi @torifat 

First of all I would like to appreciate for providing such a cool library. The Look & Feel is really awesome

I have a use case where I want to disable the Checkbox. When it is disabled it should not take the click events. Can you please guide me on how to achieve this

If it is not supported can you please provide me reference on how to enable this feature

Thansk
Pranav

**Comment by torifat** [comment]
You can actually just wrap this component inside another component and use its props to simulate a disable state. Let me know if you face any problem with that approach.
